//
//  main.c
//  zheng_david_lab7
//
//  Created by David Zheng on 10/12/18.
//  Copyright © 2018 David Zheng. All rights reserved.
//

#include "main.h"

int main(int argc, const char * argv[]) {
    char temp;
    puts("Type in a string, will return 1 if all letters, 0 therwise:");
    char s1[100];
    scanf("%[^\n]s", s1);
    char *str1 = s1;
    printf("%s%d\n\n", "The return value is:\t", all_letters(str1));
    puts("Type in a string to find the number of times characters appear within a certain range:");
    char s2[100];
    scanf("%c", &temp);
    scanf("%[^\n]s", s2);
    char *str2 = s2;
    puts("Enter lower bound:");
    char b2;
    scanf("%c", &temp);
    scanf("%c", &b2);
    puts("Enter upper bound:");
    char t2;
    scanf("%c", &temp);
    scanf("%c", &t2);
    printf("%s%d\n\n", "The number of times character between ranges appear:\t",num_in_range(str2, b2, t2));
    puts("Type the first string to be compared by how many differences in char there are:");
    char s3a[100];
    char *str3a = s3a;
    scanf("%c", &temp);
    scanf("%[^\n]s", s3a);
    puts("Type the second string to be compared by how many differences in char there are:");
    char s3b[100];
    char *str3b = s3b;
    scanf("%c", &temp);
    scanf("%[^\n]s", s3b);
    printf("%s%d\n\n", "The number of positions that the two strings differ is:\t", diff(str3a, str3b));
    puts("Type in a string to be shortened:");
    char s4[100];
    char *str4 = s4;
    scanf("%c", &temp);
    scanf("%[^\n]s", s4);
    puts("Type in the new length of the string:");
    int len4;
    scanf("%d", &len4);
    shorten(str4, len4);
    puts("Type the first string to be compared by length:");
    char s5a[100];
    char *str5a = s5a;
    scanf("%c", &temp);
    scanf("%[^\n]s", s5a);
    puts("Type the second string to be compared by length:");
    char s5b[100];
    char *str5b = s5b;
    scanf("%c", &temp);
    scanf("%[^\n]s", s5b);
    printf("%s%d\n\n", "The difference in length of the two strings is:\t", len_diff(str5a, str5b));
    puts("Type a string to have the left whitespaces removed:");
    char s6[100];
    char *str6 = s6;
    scanf("%c", &temp);
    scanf("%[^\n]s", s6);
    rm_left_space(str6);
    puts("Type a string to have the right whitespaces removed:");
    char s7[100];
    char *str7 = s7;
    scanf("%c", &temp);
    scanf("%[^\n]s", s7);
    rm_right_space(str7);
    puts("Type a string to have the all whitespaces removed:");
    char s8[100];
    char *str8 = s8;
    scanf("%c", &temp);
    scanf("%[^\n]s", s8);
    rm_space(str8);
    puts("Type in a string to find a substring for:");
    char s9a[100];
    char *str9a = s9a;
    scanf("%c", &temp);
    scanf("%[^\n]s", s9a);
    puts("Type in a substring to be found:");
    char s9b[100];
    char *str9b = s9b;
    scanf("%c", &temp);
    scanf("%[^\n]s", s9b);
    find(str9a, str9b);
    puts("Type in a string to find a substring for:");
    char s10a[100];
    char *str10a = s10a;
        scanf("%c", &temp);
    scanf("%[^\n]s", s10a);
    puts("Type in a substring to be found:");
    char s10b[100];
    char *str10b = s10b;
    scanf("%c", &temp);
    scanf("%[^\n]s", s10b);
    ptr_to(str10a, str10b);
    puts("Type in a string to be evaluated if it is empty or just white spaces:");
    char s11[100];
    char *str11 = s11;
    scanf("%c", &temp);
    scanf("%[^\n]s", s11);
    is_empty(str11);
    puts("Type in the first string to interweave:");
    char s12a[100];
    char *str12a = s12a;
    scanf("%c", &temp);
    scanf("%[^\n]s", s12a);
    puts("Type in the second string to interweave:");
    char s12b[100];
    char *str12b = s12b;
    scanf("%c", &temp);
    scanf("%[^\n]s", s12b);
    printf("The two strings interleaved is:\n%s\n\n", str_zip(str12a, str12b));
    puts("Type in a string to capitalize the first letter of each word and lowercase for all else:");
    char s13[100];
    char *str13 = s13;
    scanf("%c", &temp);
    scanf("%[^\n]s", s13);
    capitalize(str13);
    puts("Type in the first string to compare alphabetically:");
    char s14a[100];
    char *str14a = s14a;
    scanf("%c", &temp);
    scanf("%[^\n]s", s14a);
    puts("Type in the second string to compare alphabetically:");
    char s14b[100];
    char *str14b = s14b;
    scanf("%c", &temp);
    scanf("%[^\n]s", s14b);
    strcmp_ign_case(str14a, str14b);
    puts("Type in a string to show the last few characters:");
    char s15[100];
    char *str15 = s15;
    scanf("%c", &temp);
    scanf("%[^\n]s", s15);
    puts("Type in the number of characters from the back of the string to show:");
    int n15 = 0;
    scanf("%d", &n15);
    take_last(str15, n15);
    puts("Type in a string to remove all duplicate characters:");
    char s16[100];
    char *str16 = s16;
    scanf("%c", &temp);
    scanf("%[^\n]s", s16);
    printf("The new string without duplicate letters is:\n%s\n\n", dedup(str16));
    puts("Type in a string to add padding:");
    char s17[100];
    char *str17 = s17;
    scanf("%c", &temp);
    scanf("%[^\n]s", s17);
    puts("Type in a number to make the length of the string an even multiple of:");
    int n17 = 0;
    scanf("%d", &n17);
    pad(str17, n17);
    puts("Type in a string to see if it has a certain suffix:");
    char s18a[100];
    char *str18a = s18a;
    scanf("%c", &temp);
    scanf("%[^\n]s", s18a);
    puts("Type in the suffix you want to verify:");
    char s18b[100];
    char *str18b = s18b;
    scanf("%c", &temp);
    scanf("%[^\n]s", s18b);
    ends_with_ignore_case(str18a, str18b);
    puts("Insert a string to be repeated:");
    char s19[100];
    char *str19 = s19;
    scanf("%c", &temp);
    scanf("%[^\n]s", str19);
    puts("How many times do you want it to repeat?");
    int n19;
    scanf("%d", &n19);
    puts("What do you want the separator character to be?");
    char c19;
    scanf("%c", &temp);
    scanf("%c", &c19);
    repeat(str19, n19, c19);
    puts("Type in the string you want to change:");
    char s20a[100];
    char *str20a = s20a;
    scanf("%c", &temp);
    scanf("%[^\n]s", s20a);
    char s20b[100];
    char *str20b = s20b;
    puts("Type in the substring you want to change from:");
    scanf("%c", &temp);
    scanf("%[^\n]s", s20b);
    char s20c[100];
    char *str20c = s20c;
    puts("Type in the substring you want to change to:");
    scanf("%c", &temp);
    scanf("%[^\n]s", s20c);
    replace(str20a, str20b, str20c);
    char *strs21[] = {"Washington", "Adams", "Jefferson"};
    printf("Given the array of strings {%s, %s, %s}. How many elements do you want to print out?\n", strs21[0], strs21[1], strs21[2]);
    int n21;
    scanf("%c", &temp);
    scanf("%d", &n21);
    puts("What character do you want to separate the strings with?");
    char c21;
    scanf("%c", &temp);
    scanf("%c", &c21);
    puts("The new string with separators is:");
    str_connect(strs21, n21, c21);
    char *strs22[] = { "Washington", "" ,"Adams", "" , "" , "Jefferson", NULL };
    int i22 = 0;
    printf("Given the array {");
    while(strs22[i22] != NULL) {
        printf("%s, ", strs22[i22]);
        i22++;
    }
    printf("NULL}, we will remove all the empty strings.\n");
    rm_empties(strs22);
    puts("Enter a string to tokenize and put into a string array:");
    char s23[100];
    char *str23 = s23;
    scanf("%c", &temp);
    scanf("%[^\n]s", str23);
    puts("Enter a delimeter");
    char c23;
    scanf("%c", &temp);
    scanf("%c", &c23);
    str_chop_all(str23, c23);
}
